### ISSUE TITLE
KlikAanKlikUit devices not working anymore

### ISSUE THREAD

**Issue by bm480** [athombv/nl.klikaanklikuit#31] opened 2017-12-29 10:52 UTC
Just upgraded to Homey v1.5.6rc7 (coming from 1.5.3 stable) to discover that none of my KlikAanKlikUit devices are working anymore. That is, AYCT-102 remote does not trigger flows anymore and remote switches APA3-1500R, AC-300 aren't switching anymore. Homey is restarted every night, which didn't help obviously.

**Comment by bm480** [comment] 2017-12-30 21:33
After removing about 9 (inactive) apps from Homey completely and a restart, dimmers and switches magically started working again. Sadly enough, my 2 AYCT-102 remotes still don't work. Will try to re-pair them in a couple of days. Having removed a few apps (which I wasn't using anyway) makes me think that the KlikAanKlikUit not working and Homey being very slow was really a memory issue. Can someone please tell me if this could be the case?

**Comment by jeroenvollenbrock** [comment] 2018-01-10 15:43
Could you please follow the contributing guidelines and provide a little more information such as a logID right after the problem occurs.

**Comment by chinswain** [comment] 2018-02-02 21:59
Hi @jeroenvollenbrock,
I accidentally removed a device today, tried to add it back (by copying the remote) but I can no longer do this (Tried all socket switch types, homey does not detect\recognise any signal during the copy step). I have 6 devices (not klikaanklikuit but has worked ok since the klikaanklikuit app was created).

What information can I provide to assist? I can give you access to the homey with the working devices to inspect?

**Comment by jeroenvollenbrock** [comment] 2018-02-12 15:22
Should be resolved in 1.5.6-rc.13, could you please test this and report back?

**Comment by jeroenbos22** [comment] 2018-03-10 10:39
ASUN 650 stopped working here, now im on 1.5.8 but it seemed to stoped working a couple of firmware updates ago. I thought it was the fuse and tried to repair today, seems the ASUN is working fine. When trying to pair again to homey the pairing wizards shows a weird picture of the device (a small line) and no signal is ever send when generating a signal.

**Comment by BasKiers** [comment] 2018-03-13 16:21
Hi,

I was able to reproduce this issue. However, the next update of the KaKu app will be the SDK2 rewrite. For now, to work around the issue, you can still pair your ASUN device by clicking the "up" button in the test view while your ASUN is in pairing mode.

Regards,
Bas

**Comment by jeroenbos22** [comment] 2018-03-14 10:09
Hey Bas, its not pairing on the up button. Or kaku range havely decreased that it can't reach the device but highly doubt that since there is a kaku switch on the addict above the garage where the ASUN is thats working without any problems. Its just not working anymore. Like I said before in the past it worked flawless.

**Comment by BasKiers** [comment] 2018-04-05 06:40
Hi Jeroen,

I suspect this issue is caused by the memory of the ASUN being full. Did you try to do a factory reset of your ASUN?

Regards,
Bas

**Comment by RobinBol** [comment] 2018-07-09 14:20
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2645

**Closed by RobinBol** 2018-07-09 14:20 UTC
Labels: bug
